# Generated by Django 4.2.1 on 2023-05-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_aircraftpart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aircraftpart',
            table=None,
        ),
    ]
