from rest_framework import serializers

class AircraftPartSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    Part_Name = serializers.CharField()
    Material_Composition = serializers.CharField()
    Age_years = serializers.IntegerField()
    Condition = serializers.CharField()
    Location = serializers.CharField()
    Manufacturer = serializers.CharField()
    Aircraft_Model = serializers.CharField()
    Potential_Use_Cases = serializers.CharField()
    New_Parts_Carbon_Footprint_kg_CO2e = serializers.IntegerField()
    Recycled_Parts_Carbon_Footprint_kg_CO2e = serializers.IntegerField()
    water_usage_new_parts_liters = serializers.IntegerField()
    water_usage_recycled_parts_liters = serializers.IntegerField()
    landfill_waste_new_parts_kg = serializers.IntegerField()
    landfill_waste_recycled_parts_kg = serializers.IntegerField()
    energy_consumption_new_parts_kwh = serializers.IntegerField()
    energy_consumption_recycled_parts_kwh = serializers.IntegerField()
    recycling_rate_percent = serializers.FloatField()
    toxicity_score_new_parts = serializers.FloatField()
    toxicity_score_recycled_parts = serializers.FloatField()
    remanufacturing_potential = serializers.FloatField()
    life_cycle_assessment = serializers.FloatField()
    renewable_material_content_percent = serializers.FloatField()
    carbon_footprint_saved_kg_co2e = serializers.IntegerField()
    water_usage_saved_liters = serializers.IntegerField()
    landfill_waste_saved_kg = serializers.IntegerField()
    energy_consumption_saved_kwh = serializers.IntegerField()
    toxicity_score_difference = serializers.FloatField()
    remanufacturing_potential_percent = serializers.FloatField()
    life_cycle_assessment_score = serializers.FloatField()
